### ISSUE TITLE
sqlite3_adapter has conflict with new version of sqlite3 gem

### ISSUE THREAD

**Issue by VirginiaDooley** [learn-co-curriculum/rails-form_tag-lab#9] opened 2019-02-11 16:04 UTC
This error appears on several of the Rails labs on Learn.co

```Failure/Error: ActiveRecord::Migration.maintain_test_schema!

Gem::LoadError:
  Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).```

Fix can be found here: https://github.com/rails/rails/issues/35153

**Comment by jenmyers** [comment] 2019-09-25 21:08
Hi there,

I cannot reproduce this issue and I believe it has been resolved by now, so I'm going to close it.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed by jenmyers** 2019-09-25 21:08 UTC
Labels: Product
