### ISSUE TITLE
Missing Secrets.yml

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-form_tag-lab#3] opened 2016-01-07 12:24 UTC
I've cloned the curriculum version just to be able to do something this morning. I will not create a PR but will copy my work into the students version. I hope this is ok.

The lab is missing a 'secrets.yml' file in the config dir:

```
Failures:

  1) Route to view has an index page
     Failure/Error: visit students_path
     RuntimeError:
       Missing `secret_token` and `secret_key_base` for 'test' environment, set these values in `config/secrets.yml`
     # ./spec/features/student_spec.rb:5:in `block (2 levels) in <top (required)>'
```

Fix: create 'config/secrets.yml' and paste this in it:
```
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d07cfd3126c14dc8abf974c10022546b1a1d23c16485239ef1a09a299423d4e92968b3e7fd14f32177be066facdcea7d78ca54d22c394bf552ea15292262aa

test:
  secret_key_base: 1358fac7a48981852033f4d7a54c21a34272f92ca1ff35b7022de9131a1e13f5dde61b85fa439d9abfc53ba1a836e805be833b36fe0af6486641fd5a9cb69302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

```

**Comment by aviflombaum** [comment] 2016-02-09 16:27
Duplicate of #4

**Closed** 2016-02-24 18:40 UTC
